<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hitung</name>
   <tag></tag>
   <elementGuidId>dd855f73-36b8-4c50-9646-6edf775e3e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='harga-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#harga-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66469123-21ca-4a8a-a7d1-e730ca1bf722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga-img</value>
      <webElementGuid>17f54eda-4bef-41b2-b3fe-1c3bc6dbbc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/acc/hitung_harga.png</value>
      <webElementGuid>7e709485-1253-4cad-b53b-5fa65e9c19f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>f96a80ef-fc6b-4a28-b51e-1083aa309fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>hitung harga properti maksimal</value>
      <webElementGuid>82f29f19-44bb-4b6d-91b0-388717a97012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga-img&quot;)</value>
      <webElementGuid>beb6d215-79d8-41ba-9e76-7a2237a83149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='harga-img']</value>
      <webElementGuid>29ebb7dd-b215-4c0e-bda8-bd018cb041da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='harga_image']/img</value>
      <webElementGuid>fe446185-b895-4230-9467-82d765311568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='hitung harga properti maksimal'])[3]</value>
      <webElementGuid>7ab0bd83-4471-4d3d-8740-d267aa4caf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>ede09141-b62e-4bd7-9b45-6c5ab7861cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'harga-img' and @src = '/images/acc/hitung_harga.png' and @alt = 'hitung harga properti maksimal']</value>
      <webElementGuid>0fe1eda7-4003-40d2-b48e-ae23f6ebfa4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
